{{- if .Values.webhook.enabled }}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-seaweed-seaweedfs-com-v1-seaweed
  failurePolicy: Fail
  name: vseaweed.kb.io
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  rules:
  - apiGroups:
    - seaweed.seaweedfs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - seaweeds

{{- end }}
